Added bank account demo of simulation testing. (#719)
* Added bank account demo of simulation testing.

This PR includes an example of how to test Service Weaver applications
using the `sim` package. The example involves a bank that incorrectly
implements withdrawals. Specifically, the withdrawal operation

1. reads a user's bank account balance to determine if there are
   sufficient funds for the withdrawal and then
2. performs the actual withdrawal.

However, steps (1) and (2) are not performed atomically. This lack of
atomicity allows two withdrawals to race, producing a bank account with
a negative balance.

For example, consider a bank account with an initial balance of $100 and two
operations both racing to withdraw $100. The following execution is possible.

- Withdraw 1 sees a balance of $100.
- Withdraw 2 sees a balance of $100.
- Withdraw 2 withdraws, leaving a balance of $0.
- Withdraw 1 withdraws, leaving a balance of -$100.

Use the following commands to run the simulation:

```
$ cd sim/internal/bank
$ go test -v
=== RUN   TestBank
    simulator.go:288: Simulating workload *bank_test.BankWorkload for 10s.
    simulator.go:478: Executing 1 graveyard entries.
    simulator.go:315: Error found after 2 ops across 1 executions in 0s (3,064.14 execs/s, 6,128.28 ops/s).
    simulator.go:326: Failing input written to testdata/sim/TestBank/279283c821e2ac09.json.
    bank_test.go:105: sequenceDiagram
            participant op1 as Op 1
            participant op2 as Op 2
            participant github.com/ServiceWeaver/weaver/sim/internal/bank/Bank0 as bank.Bank 0
            participant github.com/ServiceWeaver/weaver/sim/internal/bank/Store0 as bank.Store 0
            note right of op1: [1:1] Withdraw(alice, 63)
            op1->>github.com/ServiceWeaver/weaver/sim/internal/bank/Bank0: [1:2] bank.Bank.Withdraw(alice, 63)
            github.com/ServiceWeaver/weaver/sim/internal/bank/Bank0->>github.com/ServiceWeaver/weaver/sim/internal/bank/Store0: [1:3] bank.Store.Get(alice)
            github.com/ServiceWeaver/weaver/sim/internal/bank/Store0->>github.com/ServiceWeaver/weaver/sim/internal/bank/Bank0: [1:3] return 100, <nil>
            note right of op2: [2:5] Withdraw(alice, 76)
            op2->>github.com/ServiceWeaver/weaver/sim/internal/bank/Bank0: [2:6] bank.Bank.Withdraw(alice, 76)
            github.com/ServiceWeaver/weaver/sim/internal/bank/Bank0->>github.com/ServiceWeaver/weaver/sim/internal/bank/Store0: [2:7] bank.Store.Get(alice)
            github.com/ServiceWeaver/weaver/sim/internal/bank/Store0->>github.com/ServiceWeaver/weaver/sim/internal/bank/Bank0: [2:7] return 100, <nil>
            github.com/ServiceWeaver/weaver/sim/internal/bank/Bank0->>github.com/ServiceWeaver/weaver/sim/internal/bank/Store0: [2:8] bank.Store.Add(alice, -76)
            github.com/ServiceWeaver/weaver/sim/internal/bank/Store0->>github.com/ServiceWeaver/weaver/sim/internal/bank/Bank0: [2:8] return 24, <nil>
            github.com/ServiceWeaver/weaver/sim/internal/bank/Bank0->>op2: [2:6] return 24, <nil>
            note right of op2: [2:5] return <nil>
            github.com/ServiceWeaver/weaver/sim/internal/bank/Bank0->>github.com/ServiceWeaver/weaver/sim/internal/bank/Store0: [1:4] bank.Store.Add(alice, -63)
            github.com/ServiceWeaver/weaver/sim/internal/bank/Store0->>github.com/ServiceWeaver/weaver/sim/internal/bank/Bank0: [1:4] return -39, <nil>
            github.com/ServiceWeaver/weaver/sim/internal/bank/Bank0->>op1: [1:2] return -39, <nil>
            note right of op1: [1:1] return user alice has negative balance -39

--- PASS: TestBank (0.00s)
PASS
ok      github.com/ServiceWeaver/weaver/sim/internal/bank       0.021s
```

The test prints out the folloing Mermaid diagram:

* Increased TestBank timeout.

The `TestBank` test was passing locally but failing on GitHub Actions
because the GitHub Actions machines are much slower.