Added WithRouter-related "weaver generate" checks.
> Check adding, deleting, or changing WithRouter.

Before this commit, if a user added, removed, or changed a
`weaver.WithRouter[T]` embedded in a component implementation but forgot
to re-run `weaver generate`, the code would compile and run, but it
would behave as it did before the change was made. This is very hard to
notice. With this commit, the code instead fails to build with a
semi-useful error message:

```
./weaver_gen.go:81:25: cannot use &foo{} (value of type *foo) as
weaver.Unrouted value in variable declaration: *foo does not implement
weaver.Unrouted (wrong type for method routedBy)
                have routedBy(router)
                want routedBy(weaver.if_youre_seeing_this_you_probably_forgot_to_run_weaver_generate)
```

To do this, we introduce two new interfaces: `weaver.RoutedBy[T]` and
`weaver.Unrouted`. When a component embeds `weaver.WithRouter[T]`, it
automatically implements `weaver.RoutedBy[T]`. Similarly, if the
component does not embed `weaver.WithRouter`, it automatically
implements `weaver.Unrouted` (more on how this is possible below).
`weaver generate` generates checks that look like the following:

```go
// weaver.Router checks.
var _ weaver.RoutedBy[router] = &routedComponent{}
var _ weaver.Unrouted = &unroutedComponent{}
```

The implementation of `weaver.RoutedBy[T]` and `weaver.Unrouted` is
quite interesting. Essentially, `weaver.Unrouted` checks that a struct
doesn't embed something?! That seems impossible at first, at least it
did to me. Here are the relevant implementation details. I've renamed
`if_youre_seeing_this_you_probably_forgot_to_run_weaver_generate` to
`private` to make things clearer. The long name is only needed to show
up in compile errors.

```go
type private struct{}

type WithRouter[T any] struct{}

func (WithRouter[T]) routedBy(T) {}

type RoutedBy[T any] interface {
    routedBy(T)
}

type Unrouted interface {
    routedBy(private)
}

type Implements[T any] struct {
    *componentImpl
}

func (*componentImpl) routedBy(private) {}
```

When a struct embeds `weaver.Implements[T]`, it inherits the
`routedBy(private)` method defined on `componentImpl` and therefore
implements the `Unrouted` interface. Later, if it embeds
`WithRouter[T]`, it inherits the the `routedBy(T)` method. Here is where
something subtle comes into play. Note that `routedBy(private)` is
embedded two levels deep inside the component struct: one level from
`Implements` and another from `componentImpl`. The `routedBy(T)` method,
on the other hand, is only embedded one level deep. Because of this, go
gives priority to the `routedBy(T)` method, and the struct implements
`RoutedBy[T]` and not `Unrouted`. If we defined `routedBy(private)` on
`Implements`, this trick would not work.

> Check deletion of router method.

Consider the following routed component:

```go
type Adder interface {
    Add(context.Context, int, int) (int, error)
}

type adder struct {
    weaver.Implements[Adder]
    weaver.WithRouter[router]
}

func (adder) Add(_ context.Context, x, y int) (int, error) {
    return x + y, nil
}

type router struct {}

func (router) Add(_ context.Context, x, y int) int {
    return x
}
```

Before this commit, if a user deleted the `router.Add` method but forgot
to re-run `weaver generate`, the code would compile and run, but the
method would be accidentally routed.

This commit generates code that does not build if a user deletes a
router method and forgets to re-run `weaver generate`. Specifically, for
every router method m on type r with signature t, we generate the
following code:

    var _ t = (&r{}).m

For the `Adder` example above, we generate the following code:

    var _ func(context.Context, int, int) int = (&router{}).Add

> Check adding of routed method.

Consider the following routed Adder component:

```go
// Component interface.
type Adder interface {
    Add(context.Context, int, int) (int, error)
    Sub(context.Context, int, int) (int, error)
}

// Component implementation.
type adder struct {
    weaver.Implements[Adder]
    weaver.WithRouter[router]
}
func (adder) Add(context.Context, int, int) (int, error) {...}
func (adder) Sub(context.Context, int, int) (int, error) {...}

// Router.
type router struct {}
func (router) Add(context.Context, int, int) (int, error) {...}
```

Note that the `Add` method is routed, but the `Sub` method is not. If
the user adds a `router.Sub` method but forgets to re-run `weaver
generate`, their code builds and runs but silently does not route the
`Sub` method like they might expect.

This commit generates code to check for the addition of a router method.
The checks require a bit of cleverness. First, you have to understand
what happens when you embed two structs with a field or method with the
same name. For example, consider the following code
(https://go.dev/play/p/bjSxzJxgjki):

```go
type a struct{ x int }
type b struct{ x int }
type s struct {
    a
    b
}
var _ = (&s{}).x
```

This code does not build because `(&s{}).x` is ambiguous. Does it refer
to `a.x` or `b.x`? We can abuse, er use, this mechanism to check that a
router does not have a given method. Going back to the `Adder` example
above, we generate the following code:

```go
type __adder_router_checker struct {
    router
    __adder_router_embedding
}

type __adder_router_embedding struct {}
func (__adder_router_embedding) Sub() {}

var _ = (&__adder_router_checker{}).Sub
```

This code compiles just fine. But, imagine a user adds a `router.Sub`
method without re-running `weaver generate`. Then,
`(&__adder_router_checker{}).Sub` becomes ambiguous and does not
compile. Does it refer to `router.Sub` or
`__adder_router_embedding.Sub`?